apiVersion: apps/v1
kind: Deployment
metadata:
  name: saas-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: saas-app
  template:
    metadata:
      labels:
        app: saas-app
    spec:
      containers:
      - name: saas-app
        image: registry.digitalocean.com/sunny-do-tam-demo/saas-app:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "100m"
            memory: "256Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"
